[Variables]
FontFace=wonderly
StringAlign=Center
AntiAlias=1
FontSize=15
Color1=255,255,255
Color2=255,0,0
Color3=0,128,128
optionValue1=Rectangle 0,0,80,80,10 | Fillcolor 29,30,36,240 | Strokewidth 2 | StrokeColor 29,30,36
optionValue2=Rectangle 0,0,125,125,10 | Fillcolor 29,30,36,240 | Strokewidth 2 | StrokeColor 29,30,36

[Background]
Meter=Shape
Shape=Rectangle 0,0,125,125,10 | Fillcolor 29,30,36,240 | Strokewidth 2 | StrokeColor 29,30,36
AntiAlias=1
DynamicVariables=1