[Variables]
FontFace=wonderly
StringAlign=Center
AntiAlias=1
;size1
Size1=9.6
Iconsize1=22.4
Iconx1=29
Icony1=29
CircularBarxy1=24
CircularBarwh1=32
LineStart1=35
LineLength1=32
porcentagemx1=51
porcentagemy1=54
textx1=38
texty1=13
optionValue1=Rectangle 0,0,80,80,10 | Fillcolor 29,30,36,240 | Strokewidth 2 | StrokeColor 29,30,36
;size2
Size2=15
Iconsize2=35
Iconx2=45
Icony2=45
CircularBarxy2=37.5
CircularBarwh2=50
LineStart2=55
LineLength2=50
porcentagemx2=80
porcentagemy2=85
textx2=60
texty2=20
optionValue2=Rectangle 0,0,125,125,10 | Fillcolor 29,30,36,240 | Strokewidth 2 | StrokeColor 29,30,36
;color
Color1=255,255,255
Color2=255,0,0
Color3=0,128,128



[Background]
Meter=Shape
Shape=Rectangle 0,0,125,125,10 | Fillcolor 29,30,36,240 | Strokewidth 2 | StrokeColor 29,30,36
AntiAlias=1
DynamicVariables=1